# DEV
services:
  app:
    build:
      target: dev
    volumes:
      - ./app:/var/www/html
      - ./app/Caddyfile:/etc/caddy/Caddyfile:ro

  app-cron:
    build:
      target: dev
    volumes:
      - ./app:/var/www/html

  mongo:
    ports:
      - "27017:27017"
