# DEV
services:
  app:
    build:
      target: dev
    volumes:
      - ./app:/var/www/html

  web:
    build:
      target: dev
    volumes:
      - ./app:/var/www/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
