import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { Readable } from 'node:stream';
import { SVGIcons2SVGFontStream } from 'svgicons2svgfont';
import svg2ttf from 'svg2ttf';
import wawoff2 from 'wawoff2';
import {
  configPath,
  linkPartialPath,
  loadIconDefinitions,
  normalizeConfig,
  outputDir,
  projectRoot,
  readJson,
  styles,
  validateConfiguredIcons
} from './lib.mjs';

const fontFamily = 'BSN Font Awesome';
const baseCodepoint = 0xe001;
const config = readJson(configPath);
const definitions = await loadIconDefinitions();

validateConfiguredIcons(config, definitions);

const entries = createEntries(config, definitions);
const hash = contentHash(entries);
const fontFileName = `fa-bsn.${hash}.woff2`;
const cssFileName = `fa-bsn.${hash}.css`;
const fontBuffer = await buildWoff2(entries);
const css = buildCss(entries, fontFileName);
const license = buildLicense(entries);

fs.mkdirSync(outputDir, { recursive: true });
fs.mkdirSync(path.dirname(linkPartialPath), { recursive: true });
removeOldGeneratedFiles(outputDir);

fs.writeFileSync(path.join(outputDir, fontFileName), fontBuffer);
fs.writeFileSync(path.join(outputDir, cssFileName), css);
fs.writeFileSync(path.join(outputDir, 'LICENSE.txt'), license);
fs.writeFileSync(linkPartialPath, `<link rel="stylesheet" href="/fontawesome/${cssFileName}">\n`);

console.log(`Built Font Awesome subset: ${entries.length} icons`);
console.log(`  /fontawesome/${cssFileName}`);
console.log(`  /fontawesome/${fontFileName}`);

function createEntries(iconConfig, iconDefinitions) {
  const normalized = normalizeConfig(iconConfig);
  let codepoint = baseCodepoint;

  return styles.flatMap((style) => {
    const styleDefinitions = iconDefinitions.get(style);
    return normalized.get(style).map((name) => {
      const definition = styleDefinitions.get(name);
      const entry = {
        style,
        name,
        glyphName: `${style}-${name}`,
        codepoint,
        definition
      };
      codepoint += 1;
      return entry;
    });
  });
}

async function buildWoff2(entries) {
  const svgFont = await buildSvgFont(entries);
  const ttf = svg2ttf(svgFont, {});
  const ttfBuffer = Buffer.from(ttf.buffer);
  return Buffer.from(await wawoff2.compress(ttfBuffer));
}

function buildSvgFont(entries) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const fontStream = new SVGIcons2SVGFontStream({
      fontName: fontFamily,
      fontHeight: 512,
      normalize: true,
      centerHorizontally: true
    });

    fontStream.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    fontStream.on('error', reject);
    fontStream.on('finish', () => resolve(Buffer.concat(chunks).toString('utf8')));

    for (const entry of entries) {
      const glyph = Readable.from([iconDefinitionToSvg(entry.definition)]);
      glyph.metadata = {
        unicode: [String.fromCodePoint(entry.codepoint)],
        name: entry.glyphName
      };
      fontStream.write(glyph);
    }

    fontStream.end();
  });
}

function iconDefinitionToSvg(definition) {
  const [width, height, , , svgPathData] = definition.icon;
  const paths = Array.isArray(svgPathData) ? svgPathData : [svgPathData];
  const pathMarkup = paths.map((pathData) => `<path d="${pathData}"/>`).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${pathMarkup}</svg>`;
}

function buildCss(entries, fontFileName) {
  const lines = [
    '/* Generated by npm run fa_build. Do not edit manually. */',
    '@font-face {',
    `  font-family: "${fontFamily}";`,
    `  src: url("/fontawesome/${fontFileName}") format("woff2");`,
    '  font-style: normal;',
    '  font-weight: 400;',
    '  font-display: block;',
    '}',
    '',
    '.fa-solid,',
    '.fa-regular,',
    '.fa-brands {',
    `  font-family: "${fontFamily}";`,
    '  font-style: normal;',
    '  font-weight: 400;',
    '  line-height: 1;',
    '  display: inline-block;',
    '  text-rendering: auto;',
    '  -webkit-font-smoothing: antialiased;',
    '  -moz-osx-font-smoothing: grayscale;',
    '}',
    '',
    '.fa-xs { font-size: 0.75em; }',
    '.fa-sm { font-size: 0.875em; }',
    '.fa-lg { font-size: 1.25em; }',
    '.fa-xl { font-size: 1.5em; }',
    '.fa-2xl { font-size: 2em; }',
    '.fa-fw { width: 1.25em; text-align: center; }',
    '.fa-flip-horizontal { transform: scaleX(-1); }',
    '.fa-flip-vertical { transform: scaleY(-1); }',
    ''
  ];

  for (const entry of entries) {
    lines.push(`.fa-${entry.style}.fa-${entry.name}::before { content: "\\${entry.codepoint.toString(16)}"; }`);
  }

  return `${lines.join('\n')}\n`;
}

function contentHash(entries) {
  const packageVersions = {
    solid: readJson(path.join(projectRoot, 'node_modules/@fortawesome/free-solid-svg-icons/package.json')).version,
    regular: readJson(path.join(projectRoot, 'node_modules/@fortawesome/free-regular-svg-icons/package.json')).version,
    brands: readJson(path.join(projectRoot, 'node_modules/@fortawesome/free-brands-svg-icons/package.json')).version
  };

  const hashInput = {
    cssVersion: 1,
    fontVersion: 1,
    packageVersions,
    icons: entries.map((entry) => ({
      style: entry.style,
      name: entry.name,
      codepoint: entry.codepoint,
      icon: entry.definition.icon
    }))
  };

  return crypto.createHash('sha256').update(JSON.stringify(hashInput)).digest('hex').slice(0, 12);
}

function buildLicense(entries) {
  const stylesUsed = [...new Set(entries.map((entry) => entry.style))].join(', ');
  return [
    'This directory contains a generated subset of Font Awesome Free.',
    '',
    `Styles used: ${stylesUsed}`,
    'Source: https://fontawesome.com',
    'License: CC BY 4.0 License for icons, SIL OFL 1.1 License for fonts, MIT License for code.',
    'See installed @fortawesome/free-*-svg-icons packages for the full license text.',
    ''
  ].join('\n');
}

function removeOldGeneratedFiles(dir) {
  for (const fileName of fs.readdirSync(dir)) {
    if (/^fa-bsn\.[a-f0-9]{12}\.(css|woff2)$/.test(fileName) || fileName === 'LICENSE.txt') {
      fs.rmSync(path.join(dir, fileName));
    }
  }
}
