VERSION = "2.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

FEDERATION_SERVER = "https://bsn.expert/federation"

URI_REQUEST_SIGNING_KEY = "GA7R23EX6H6CQUMUVJFNJ6YCNXPM3WJNZD2OJOWUH75ZDFWL4TEQBSNS"
SIGNING_KEY = "GA7R23EX6H6CQUMUVJFNJ6YCNXPM3WJNZD2OJOWUH75ZDFWL4TEQBSNS"

ACCOUNTS = [
    "GBY743WRLF4APZ2D6DSRQBIGVDGME65QIQXONN4E52CEDRCQ2VIMEBSN"
]

[DOCUMENTATION]
ORG_NAME = "BSN.Expert"
ORG_URL = "https://bsn.expert"
ORG_SUPPORT_EMAIL = "info@bsn.expert"